//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Entities
{
    using System;
    
    public partial class ArchivedInboxOfSelectedProfilesProcedure_Result1
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string StatusId { get; set; }
        public string MemberName { get; set; }
        public string ProfilePic { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string UserName { get; set; }
        public string TextValue { get; set; }
        public string FromUser { get; set; }
        public string ToUser { get; set; }
        public Nullable<bool> IsPage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ActivityType { get; set; }
        public Nullable<bool> IsRetweet { get; set; }
        public int IsTask { get; set; }
        public int IsTaskCompleted { get; set; }
        public string Keywords { get; set; }
    }
}
