//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelScore
    {
        public int Id { get; set; }
        public int MediaTypeId { get; set; }
        public int NewsTypeId { get; set; }
        public int SentimentId { get; set; }
        public string TimSlot { get; set; }
        public int Score { get; set; }
        public int ChannelId { get; set; }
    
        public virtual NewsType NewsType { get; set; }
        public virtual Sentiment Sentiment { get; set; }
    }
}
