//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDReportFilter
    {
        public int Id { get; set; }
        public string ReportType { get; set; }
        public string ChannelIds { get; set; }
        public string FilterType { get; set; }
    }
}
